title: "Valon Haslem"
description: "Applied Math & Economics"
theme: jekyll-theme-minima   # change this to any supported jekyll-theme-*
# baseurl: "" # set if repo is not user/organization page
url: https://vhaslem.github.io # your site URL for absolute_url helpers
lang: en
author:
  name: "Valon Haslem"
  email: "valondhaslem@gmail.com"

# optional: social links used by layout
social:
  - name: GitHub
    url: https://github.com/vhaslem
  - name: LinkedIn
    url: https://www.linkedin.com/in/valon-haslem-b69751291/